<a href="https://colab.research.google.com/github/uroojhanif78-coder/Numpy.Task/blob/main/numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# task : 1

import numpy as np

marks = np.array([10, 20, 30, 40, 50])



print(np.sum(marks))
print(np.mean(marks))
print(np.min(marks))
print(np.max(marks))

150
30.0
10
50


In [ ]:
# task : 2
import numpy as np

marks = np.array([40, 80, 30, 90, 55, 20])

greatest = marks[marks >= 50]
print(greatest)

[80 90 55]


In [ ]:
# task : 3
import numpy as np

numbers = np.array([1, 2, 3, 4, 5, 6])

new_array = numbers.reshape(2,3)
print(new_array)



[[1 2 3]
 [4 5 6]]


In [ ]:
# task : 4
import numpy as np

marks = np.random.randint(40, 100, 10)
print(marks)

print(np.mean(marks))
print(np.max(marks))
print(np.min(marks))

[60 84 71 68 80 41 40 52 97 56]
64.9
97
40


In [ ]:
# task 5
import numpy as np

marks = np.array([37, 67, 89, 45, 22, 90, 70, 58])

passed = marks[marks >= 50]
failed = marks[marks < 50]

print("\nPassed Students Marks:")
print(passed)

print("Failed Students Marks:")
print(failed)



Passed Students Marks:
[67 89 90 70 58]
Failed Students Marks:
[37 45 22]


in class

In [ ]:
import numpy as np
marks = [56,90,45,69,80,70]

avg_marks = (np.mean(marks))
print(avg_marks)

highest_marks = (np.max(marks))
print(highest_marks)

lowest_marks = (np.min(marks))
print(lowest_marks)

marks = np.array(marks)
passed = marks[marks >= 50]
print(passed)

failed = np.array(marks)
failed = marks[marks < 50]
print(failed)

68.33333333333333
90
45
[56 90 69 80 70]
[45]


In [ ]:
# HANDS ON
import numpy as np

marks = np.array([5, 10, 15, 20, 25])

print(marks + 5)
print(marks - 2)
print(marks * 3)
print(marks / 2)

[10 15 20 25 30]
[ 3  8 13 18 23]
[15 30 45 60 75]
[ 2.5  5.   7.5 10.  12.5]


In [ ]:
# max , min, sum & avg

marks = np.array([10, 15, 20, 25, 30, 35, 40,45])

print(np.max(marks))
print(np.min(marks))
print(np.sum(marks))
print(np.mean(marks))

45
10
220
27.5


In [ ]:
# shape + indexing


marks = np.array([
            [20, 30, 40, 70],
            [10, 20, 30, 40]
])
print(marks.shape)
print(marks[0,2])

(2, 4)
40


In [ ]:
# Indexing in a 2D array

marks = np.array([
       [50,40,70,30,80],
       [40,60,30,80,70]
       ])
print(marks[0, 2])
print(marks[1,-3])

70
30


In [ ]:
# Absolute value

marks = np.array([70,40,30,50])
print(marks[3])
print(marks[-2])

50
30


In [ ]:
marks = np.array([70,30,40,90,80])

print(marks[0])
print(marks[-2])

70
90


In [ ]:
import numpy as np
print(np.zeros(5))
print(np.ones(5))

[0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1.]


In [ ]:
# arange
print(np.arange(1,20))

print(np.arange(1,20,2))


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 1  3  5  7  9 11 13 15 17 19]


In [ ]:
# random

marks = np.random.randint(25,110,20)

print(marks)

[108  89  47  74  49  60 100  71 108  27  93  94  80  56 103  46  41  30
  70  87]


In [ ]:
# flatten

data = np.array([
    [40,30,20],
    [60,30,50]

])
print(data.flatten())

[40 30 20 60 30 50]


In [ ]:
# operation between wo arrays
a = np.array([10,30,20,30])
b = np.array([2,3,2,5])

print(a + b)
print(a * b)

[12 33 22 35]
[ 20  90  40 150]


In [ ]:
# shape #ndim #size #dtype

import numpy as np
marks = np.array([
    [20, 10, 16, 28, 30],
    [15, 30, 25, 18, 20]
])
print(marks.shape)
print(marks.ndim)
print(marks.size)
print(marks.dtype)

(2, 5)
2
10
int64


In [ ]:
#Zeros & #Ones
print(np.zeros(10))
print(np.ones(10))

#arange
print(np.arange(1,21))
#even
print(np.arange(10,30,2))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[10 12 14 16 18 20 22 24 26 28]
